<a href="https://colab.research.google.com/github/Swapnilss53/Full-stack-data-science-PWSKILLS-/blob/main/Numpy_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. What is a Python library? Why do we use Python libraries?


Python Library : A Python library is a collection of related modules. It contains bundles of code that can be used repeatedly in different programs. In simple terms most efficient and advance function are written by coders and we can use them for our use. it helps in reducing our time of writing any function from scratch

Why do we use python library : The simple reason for using libary is it saves our time and the code written was most efficient and well tested hence it gives us better performance.
   we can use that code again and again .
they helps us avoid writing the same code again and again

2. What is the difference between Numpy array and List?



*   Numpy array


> 1.   Numpy arrays are Homogeneous meaning they contain same data type for each element
2.   Numpy arrays consumes less memory because they are static.
3. Numpy arrays are fatser than list because they are homogeneous in nature and numpy is written in c++ which is fasted programming language
4. Numpy arrays support element wise operations meaning
```
a =[1,2,3]
b =[4,5,6]
c = a+b
output: c= [5,7,9] in terms of numpy array
```
5. The size of a Numpy array is fixed at time of creation
6. Elements in numpy array are stored in a contiguous manner in memory

* List


> 1.   Python list can be heterogeneous means they can contain elemnt of different data type
2.   list consumes less  memeory
3. lists are slower compared to Numpy array
4. element wise operaaion is not possible with python list
```
a =[1,2,3]
b =[4,5,6]
c = a+b
output: c= [1,2,3,4,5,6] in terms of python list
```
5.list are dynamic and can grow and shrink in size
6. Elemnts in python list are stored at random location in memory













  




3. Find the shape, size and dimension of the following array?


> ```
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]
```





In [ ]:
import numpy as np

arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])

#printing aray
print(f"arr = \n{arr}")

#shape of array
print(f"The shape of array is := {arr.shape}")

#size of array
print(f"The size of array is = {arr.size}")

# Dimension of array
print(f"The dimension of array is = {arr.ndim}")

arr = 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
The shape of array is := (3, 4)
The size of array is = 12
The dimension of array is = 2


4. Write python code to access the first row of the following array?


> ```
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]
```

In [ ]:
import numpy as np

arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,10]])

#printing aray
print(f"arr = \n{arr}")

#printing first row of the array
print(f"The first row is : {arr[0]}")

arr = 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 10]]
The first row is : [1 2 3 4]


5. How do you access the element at the third row and fourth column from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [ ]:
import numpy as np

arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])

print(f"The element at third row and fourth column from array is : {arr[2][3]}")

The element at third row and fourth column from array is : 12


6. Write code to extract all odd-indexed elements from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [2]:
import numpy as np

arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])

odd_indexed_elements = arr[:, 1::2]

print(odd_indexed_elements)

[[ 2  4]
 [ 6  8]
 [10 12]]


7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [ ]:
import numpy as np

random_arr = np.random.rand(3,3)

random_arr

array([[0.36184218, 0.44807889, 0.03261679],
       [0.66934131, 0.01852382, 0.20761988],
       [0.39484984, 0.133964  , 0.90649807]])

8. Describe the difference between np.random.rand and np.random.randn?



### **ANS :=**


*   np.random.rand: This function creates an array of the given shape and populates it with random samples from a uniform distribution over [0, 1). That is, it generates numbers between 0 (inclusive) and 1 (exclusive)
*   np.random.randn: This function returns a sample from the “standard normal” distribution, more commonly known as a Gaussian distribution. Unlike rand which is uniform, values closer to zero are more likely to appear



9. Write code to increase the dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

#printing the originial dimesion of array
print(f"Older dimension is {arr.ndim}")

arr_with_new_dim = np.expand_dims(arr,0)

#printing dimension after increasing it
print(f"The dimension after increasing is := {arr_with_new_dim.ndim}")

Older dimension is 2
The dimension after increasing is := 3


10. How to transpose the following array in NumPy?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [ ]:
import numpy as np

arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]
                ])

print(f"Array before transpose is := \n{arr}")

transposed_array = arr.T

print('\n')

print(f"Arry after transpose is := \n{transposed_array}")

Array before transpose is := 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Arry after transpose is := 
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


11. Consider the following matrix:
Matrix A: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Matrix B: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]


Perform the following operation using Python



1.   Index whise multiplication
2.   Matix multiplication
3.   Add both the matics
4.   Subtact matix B From A
5.   Divide Matix B by A







In [ ]:
import numpy as np

A = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])

B = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])


# 1. Index wise multiplication
index_mul = A * B
print(f"Index wise multiplication of A and B is := \n{index_mul}\n")

# 2. Matrix Multiplication
#while multyplying using matrix multiplication we need to have axb cxd where we need b===c so we need to take transpose first
transposed_b = B.T
matrix_mul = A @ transposed_b
print(f"Matrix Multiplication of A and B is := \n{matrix_mul}\n")

#3. Add both the matrix
addition = A + B
print(f"The addition of A and B is := \n{addition}\n")

#4. Subtract matrix B from A
subtract =  B - A
print(f"Subtraction of matrix B from  A is :=\n{subtract}\n")

#5. Divide matrix B by A
divide = B / A
print(f"Divion of matrix B by matrix A is :=\n{divide}\n")

Index wise multiplication of A and B is := 
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]

Matrix Multiplication of A and B is := 
[[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]

The addition of A and B is := 
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]

Subtraction of matrix B from  A is :=
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

Divion of matrix B by matrix A is :=
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]



12. Which function in Numpy can be used to swap the byte order of an array?



*   this is the function to swap byte order of an array


byteswap() := function toggle between low-endian and big-endian data representation by returning a byteswapped array, optionally swapped in-place



```
import numpy as geek
  
# a is an array of integers.
a = geek.array([1, 256, 100], dtype = np.int16)
   
print(a.byteswap(True))
```
this function not work for string array


13. What is the significance of the np.linalg.inv function?

The np.linalg.inv() function is used to compute the inverse of a square matrix
the significance is in linear algebra,  machine learning and data science it is used to solve the equation

14. What does the np.reshape function do, and how is it used?

np.reshape function is used to give a new shape to an array without changing its data



```
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6])

# Reshape the array
reshaped_a = np.reshape(a, (2, 3))

print(reshaped_a)
```
the funtion is used as per above implementation
this function take 2 argument first the array which needed to be reshaped and the second argument is in which shape you want to reshape it  here we need to give the the row and column in which you want to transform it




15. What is broadcasting in Numpy?

Broadcasting in Numpy is  term that describes how Numpy treats arrays with different shapes during arithmetic operations
the smaller array is broadcast across the larger array so that they have compatible shapes.
this terms means that  addition,subtraction, division can be done on each of the element of array

